
person = '{' , name , age , dob , '}' ;


name = firstName , ',' , lastName, ';' ;

firstName = common:alphStrDQ ;

lastName = common:alphStrDQ ;


age = posInt , ';' ;

posInt = common:positiveInt ;

dob = date , ';' ;

date = common:date ; 

# boilerplate constructions, should be simplified somehow...

